server:
  port: 80
  servlet:
    context-path: /sso

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useAffectedRows=true
    username: root
    password: root
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    minIdle: 50
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60000
    jedis:
      pool:
        max-active: 1000
        max-idle: 600
        max-wait: -1
        min-idle: 0