spring:
  profiles:
    active: dev
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      maxFileSize: 10MB
      maxRequestSize: 10MB
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.eatime.mapper
  configuration:
    mapUnderscoreToCamelCase: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

