server:
  port: 80
  context-path: /sso
#配置
cfg:
  serverPath: C:/Program Files/Apache Software Foundation/Tomcat 8.0/webapps
  filePath: C:/Program Files/Apache Software Foundation/Tomcat 8.0/webapps/file
  oss:
    endPoint: oss-cn-qingdao.aliyuncs.com
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_dev
    username: root
    password: root

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60000
    pool:
      max-active: 1000
      max-idle: 600
      max-wait: -1
      min-idle: 0

#  spring.mail.properties.smtp.auth=true
#  spring.mail.properties.smtp.starttls.enable=true
#  spring.mail.properties.smtp.starttls.required=true
#  spring.mail.properties.mail.smtp.ssl.enable=true
  mail:
    host: smtp.163.com
    port: 25
    username: zyf69172@163.com
    password:
#debug模式下不发送短信邮箱等验证码
debug: false