server:
  port: 80
  context-path: /sso
#配置
cfg:
  serverPath: /opt/apache-tomcat-8.0.50/webapps
  filePath: /opt/apache-tomcat-8.0.50/webapps/file
  oss:
    endPoint: vpc100-oss-cn-qingdao.aliyuncs.com
spring:
  datasource:
    url:
    username:
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    minIdle: 50
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20  
  session: 
#    设置spring-session存储类型
    store-type: hash-map
  redis:
    host:
    port: 6379
    timeout: 60000
    password:
    database:
    pool:
      max-active: 1000
      max-idle: 600
      max-wait: -1
      min-idle: 0